"""Add azure_ad_oid to users, make password nullable

Revision ID: 268f6d2e9c13
Revises: d5fa944353bb
Create Date: 2026-03-29 22:37:30.913035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '268f6d2e9c13'
down_revision: Union[str, None] = 'd5fa944353bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('azure_ad_oid', sa.String(length=255), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.create_index(op.f('ix_users_azure_ad_oid'), 'users', ['azure_ad_oid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_azure_ad_oid'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('users', 'azure_ad_oid')
    # ### end Alembic commands ###
