"""Initial schema

Revision ID: d5fa944353bb
Revises: 
Create Date: 2026-03-29 22:09:46.734386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5fa944353bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_loan_id'), 'audit_events', ['loan_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('encompass_instance_id', sa.String(length=255), nullable=True),
    sa.Column('encompass_client_id', sa.Text(), nullable=True),
    sa.Column('encompass_client_secret_ref', sa.String(length=512), nullable=True, comment='Reference to secret in vault, never the actual secret'),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'LOAN_OFFICER', 'UNDERWRITER', 'PROCESSOR', 'BORROWER', name='userrole'), nullable=False),
    sa.Column('encompass_user_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encompass_loan_id', sa.String(length=50), nullable=True),
    sa.Column('encompass_loan_number', sa.String(length=50), nullable=True),
    sa.Column('loan_officer_id', sa.UUID(), nullable=True),
    sa.Column('primary_borrower_persona', sa.Enum('W2_SALARIED', 'SELF_EMPLOYED', 'COMMISSION_VARIABLE', 'RETIRED_FIXED', 'RENTAL_INCOME', name='borrowerpersona'), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'INTAKE', 'PROCESSING', 'SUBMITTED_TO_UW', 'CONDITIONALLY_APPROVED', 'CLEAR_TO_CLOSE', 'CLOSING', 'FUNDED', 'SUSPENDED', 'DENIED', name='loanstatus'), nullable=False),
    sa.Column('processing_phase', sa.Enum('INTAKE', 'AUS_CREDIT', 'DOC_COLLECTION', 'DATA_VERIFICATION', 'THIRD_PARTY', 'UW_SUBMISSION', 'CLOSING', name='processingphase'), nullable=False),
    sa.Column('encompass_milestone', sa.String(length=100), nullable=True),
    sa.Column('loan_purpose', sa.String(length=50), nullable=True),
    sa.Column('occupancy_type', sa.String(length=50), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('loan_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('appraised_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('loan_term_months', sa.Integer(), nullable=True),
    sa.Column('ltv', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('cltv', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('dti_front', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('dti_back', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('qualifying_income_monthly', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('aus_type', sa.String(length=10), nullable=True),
    sa.Column('aus_finding', sa.String(length=50), nullable=True),
    sa.Column('aus_case_id', sa.String(length=50), nullable=True),
    sa.Column('credit_score_borrower', sa.Integer(), nullable=True),
    sa.Column('credit_score_coborrower', sa.Integer(), nullable=True),
    sa.Column('representative_credit_score', sa.Integer(), nullable=True),
    sa.Column('ai_readiness_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='0-100 score indicating how ready the file is for UW'),
    sa.Column('loan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_encompass_loan_id'), 'loans', ['encompass_loan_id'], unique=True)
    op.create_index(op.f('ix_loans_encompass_loan_number'), 'loans', ['encompass_loan_number'], unique=False)
    op.create_index('ix_loans_lo_status', 'loans', ['loan_officer_id', 'status'], unique=False)
    op.create_index(op.f('ix_loans_status'), 'loans', ['status'], unique=False)
    op.create_index('ix_loans_status_phase', 'loans', ['status', 'processing_phase'], unique=False)
    op.create_index(op.f('ix_loans_tenant_id'), 'loans', ['tenant_id'], unique=False)
    op.create_table('agent_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_version', sa.String(length=20), nullable=False),
    sa.Column('validation_type', sa.String(length=100), nullable=False),
    sa.Column('input_document_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'ESCALATE', name='confidencelevel'), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_tokens_used', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_validations_agent_name'), 'agent_validations', ['agent_name'], unique=False)
    op.create_index('ix_agent_validations_loan_agent', 'agent_validations', ['loan_id', 'agent_name'], unique=False)
    op.create_index(op.f('ix_agent_validations_loan_id'), 'agent_validations', ['loan_id'], unique=False)
    op.create_index(op.f('ix_agent_validations_tenant_id'), 'agent_validations', ['tenant_id'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('encompass_condition_id', sa.String(length=100), nullable=True),
    sa.Column('condition_type', sa.Enum('PTD', 'PTF', 'PTC', 'POST_CLOSING', name='conditiontype'), nullable=False),
    sa.Column('source', sa.Enum('AUS', 'UNDERWRITER', 'SYSTEM', 'COMPLIANCE', name='conditionsource'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'REQUESTED', 'RECEIVED', 'REVIEWED', 'CLEARED', 'WAIVED', name='conditionstatus'), nullable=False),
    sa.Column('required_document_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('linked_document_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('cleared_by_agent', sa.String(length=100), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_by_user_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_loan_id'), 'conditions', ['loan_id'], unique=False)
    op.create_index('ix_conditions_loan_status', 'conditions', ['loan_id', 'status'], unique=False)
    op.create_index(op.f('ix_conditions_status'), 'conditions', ['status'], unique=False)
    op.create_index(op.f('ix_conditions_tenant_id'), 'conditions', ['tenant_id'], unique=False)
    op.create_table('loan_borrowers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('borrower_type', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('ssn_hash', sa.String(length=128), nullable=True, comment='Salted hash, never raw SSN'),
    sa.Column('persona', sa.Enum('W2_SALARIED', 'SELF_EMPLOYED', 'COMMISSION_VARIABLE', 'RETIRED_FIXED', 'RENTAL_INCOME', name='borrowerpersona'), nullable=True),
    sa.Column('encompass_borrower_id', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('years_in_profession', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('self_employed', sa.Boolean(), nullable=True),
    sa.Column('ownership_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('income_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_borrowers_loan_id'), 'loan_borrowers', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_borrowers_tenant_id'), 'loan_borrowers', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=True),
    sa.Column('encompass_document_id', sa.String(length=100), nullable=True),
    sa.Column('encompass_attachment_id', sa.String(length=100), nullable=True),
    sa.Column('document_type', sa.Enum('W2', 'PAY_STUB', 'TAX_RETURN_1040', 'TAX_RETURN_BUSINESS', 'SCHEDULE_C', 'SCHEDULE_E', 'K1', 'FORM_1099', 'FORM_1099_R', 'PL_STATEMENT', 'BALANCE_SHEET', 'BUSINESS_LICENSE', 'CPA_LETTER', 'EMPLOYMENT_CONTRACT', 'SS_AWARD_LETTER', 'PENSION_STATEMENT', 'BANK_STATEMENT', 'RETIREMENT_STATEMENT', 'GIFT_LETTER', 'EARNEST_MONEY_RECEIPT', 'VOE_VERBAL', 'VOE_WRITTEN', 'CREDIT_REPORT', 'LOE_CREDIT', 'PURCHASE_CONTRACT', 'APPRAISAL', 'TITLE_COMMITMENT', 'HOI_DECLARATION', 'FLOOD_CERT', 'HOA_DOCS', 'CONDO_QUESTIONNAIRE', 'LEASE_AGREEMENT', 'MORTGAGE_STATEMENT', 'PROPERTY_TAX_BILL', 'PHOTO_ID', 'SSN_AUTHORIZATION', 'FORM_4506_C', 'IRS_TRANSCRIPT', 'DIVORCE_DECREE', 'CHILD_SUPPORT_ORDER', 'BANKRUPTCY_DISCHARGE', 'LOE_GENERAL', 'CLOSING_DISCLOSURE', 'LOAN_ESTIMATE', 'OTHER', name='documenttype'), nullable=True),
    sa.Column('category', sa.Enum('INCOME', 'ASSETS', 'PROPERTY', 'TITLE', 'INSURANCE', 'CREDIT', 'LEGAL', 'COMPLIANCE', 'CLOSING', 'OTHER', name='documentcategory'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False, comment='S3 key'),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='SHA-256 for dedup'),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('classification_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'CLASSIFYING', 'CLASSIFIED', 'EXTRACTING', 'EXTRACTED', 'VALIDATING', 'VALIDATED', 'REJECTED', 'NEEDS_REVIEW', name='documentstatus'), nullable=False),
    sa.Column('period_start', sa.String(length=10), nullable=True),
    sa.Column('period_end', sa.String(length=10), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['loan_borrowers.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_loan_id'), 'documents', ['loan_id'], unique=False)
    op.create_index('ix_documents_loan_type', 'documents', ['loan_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('from_type', sa.String(length=20), nullable=False),
    sa.Column('from_id', sa.String(length=255), nullable=True),
    sa.Column('to_user_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.Enum('NEEDS_LIST', 'CLARIFICATION', 'STATUS_UPDATE', 'ESCALATION', 'LOE_REQUEST', 'DOC_DEFICIENCY', name='messagetype'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('related_condition_id', sa.UUID(), nullable=True),
    sa.Column('related_document_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['related_condition_id'], ['conditions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_loan_id'), 'messages', ['loan_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_loan_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index('ix_documents_loan_type', table_name='documents')
    op.drop_index(op.f('ix_documents_loan_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_loan_borrowers_tenant_id'), table_name='loan_borrowers')
    op.drop_index(op.f('ix_loan_borrowers_loan_id'), table_name='loan_borrowers')
    op.drop_table('loan_borrowers')
    op.drop_index(op.f('ix_conditions_tenant_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_status'), table_name='conditions')
    op.drop_index('ix_conditions_loan_status', table_name='conditions')
    op.drop_index(op.f('ix_conditions_loan_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_agent_validations_tenant_id'), table_name='agent_validations')
    op.drop_index(op.f('ix_agent_validations_loan_id'), table_name='agent_validations')
    op.drop_index('ix_agent_validations_loan_agent', table_name='agent_validations')
    op.drop_index(op.f('ix_agent_validations_agent_name'), table_name='agent_validations')
    op.drop_table('agent_validations')
    op.drop_index(op.f('ix_loans_tenant_id'), table_name='loans')
    op.drop_index('ix_loans_status_phase', table_name='loans')
    op.drop_index(op.f('ix_loans_status'), table_name='loans')
    op.drop_index('ix_loans_lo_status', table_name='loans')
    op.drop_index(op.f('ix_loans_encompass_loan_number'), table_name='loans')
    op.drop_index(op.f('ix_loans_encompass_loan_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_loan_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
